# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later
---
evaka:
  email:
    sender_address: "no-reply.evaka@espoo.fi"
    sender_name:
      fi: "Espoon Varhaiskasvatus"
      sv: "Esbo sm√•barnspedagogik"
    application_received:
      sender_address:
        fi: "vaka.palveluohjaus@espoo.fi"
        sv: "dagis@esbo.fi"
      sender_name:
        fi: "Varhaiskasvatuksen palveluohjaus"
        sv: "Barninvalskoordinatorer / Esbo stad"
  oph:
    municipality_code: "049"
    organizer_oid: "1.2.246.562.10.90008375488"
    organizer_id: "299"
  integration:
    sfi:
      contact_organization:
        name: "eVaka Espoo"
        street_address: "Karaportti 1 PL 30"
        postal_code: "02070"
        post_office: "Espoo"