# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

# Use this compose file to extend docker-compose.yml when you want to run
# the latest published versions, e.g. for E2E testing.
version: "3.5"

services:
  playwright:
    image: public.ecr.aws/p6g0g5e1/evaka/e2e-playwright:${PLAYWRIGHT_TAG:-v0.2.0-test-2-github}
    build:
      context: ./e2e
      dockerfile: ./playwright.Dockerfile
    volumes:
      - ..:/repo
    ipc: host
    network_mode: host
    environment:
      HEADLESS: ${HEADLESS:-true}
      DEBUG: ${DEBUG:-}
    depends_on:
      - keycloak
      - evaka-proxy
      - enduser-gw
      - internal-gw
      - evaka-srv
