# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

# Docker Compose file that can be used for development builds and that links
# against the development Docker files. Do not mistaken these with production
# docker files that the other compose files deal with.
#
# Tips and Tricks
# ===============
#
# If you need to target a local service instead you can use
# a pseudo address docker.for.mac.localhost when running on macOS.
# E.g. to target local application service set APPLICATION_API_URL: http://docker.for.mac.localhost:8080
version: '3.5'

services:
  db:
    image: ghcr.io/espoon-voltti/evaka/test-db:${TEST_DB_TAG:-master}
    build:
      context: ./db/
      cache_from:
        - ghcr.io/espoon-voltti/evaka/test-db:cache-${CACHE_TAG:-master}
        - ghcr.io/espoon-voltti/evaka/test-db:cache-master
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 2s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:8.1-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: '[ "$$(valkey-cli -h 127.0.0.1 ping)" == "PONG" ]'
      interval: 1s
      timeout: 5s
      retries: 5

  s3-mock:
    image: adobe/s3mock:4.5.0
    ports:
      - "9876:9191"
    volumes:
      - s3-data:/data
    environment:
      ROOT: /data
      initialBuckets: "static"
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0 -XX:+IgnoreUnrecognizedVMOptions"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090"]
      interval: 1s
      timeout: 5s
      retries: 5

  sftp:
    image: atmoz/sftp:alpine
    ports:
      - "2222:22"
    volumes:
      - ./sftp/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./sftp/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
    command: foo:pass:::upload

  dummy-idp:
    build:
      context: ../dummy-idp
    init: true
    restart: on-failure
    ports:
      - "9090:9090"

volumes:
  db-data:
    driver: local
  s3-data:
    driver: local
